name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza diariamente à meia-noite
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch GitHub Stats
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -H "Authorization: token $GH_TOKEN" \
          "https://github-readme-stats.vercel.app/api?username=ernestosrf&show_icons=true&theme=radical&include_all_commits=true&count_private=true" > stats.svg

    - name: Update README
      run: |
        echo '## GitHub Stats' > README.md
        echo '![](./stats.svg)' >> README.md
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add README.md stats.svg
        git commit -m "Updated README with GitHub Stats"
        git push
